
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Kapital

    steps:
    - uses: actions/checkout@v4
    - name: Linting
      run: ./gradlew lintDebug
      
    - name: upload Html lint report
      uses: actions/upload-artifact@v2
      with:
        name: index.html
        path: app/build/reports/lint-results-debug.html
        
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.x'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    # - name: Archive build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: app-artifact
    #     path: app/build/reports/...
